import { createStore, combineReducers } from "redux";
import {
  setactiveentity,
  setactiveuserslist,
  setalerts,
  setapprovedpendingmessageslist,
  setauthentication,
  setcallslist,
  setcontactslist,
  setconversationsetup,
  setcoordinates,
  setemojilist,
  setistypinglist,
  setmediamyvideoholder,
  setmediatrackholder,
  setmessageslist,
  setminimizedconversation,
  setnotificationslist,
  setpagemodal,
  setpathnamelistener,
  setpendingcallalerts,
  setpendingmessageslist,
  setpostsfeedlist,
  setpreviewparticipant,
  setrawcoordinates,
  setrejectedcalllist,
  setscreensizelistener,
  settogglerightwidget,
  setusersettings,
} from "../actions";

const combiner = combineReducers({
  authentication: setauthentication,
  activeentity: setactiveentity,
  alerts: setalerts,
  contactslist: setcontactslist,
  notificationslist: setnotificationslist,
  messageslist: setmessageslist,
  conversationsetup: setconversationsetup,
  togglerightwidget: settogglerightwidget,
  screensizelistener: setscreensizelistener,
  pathnamelistener: setpathnamelistener,
  pendingmessageslist: setpendingmessageslist,
  approvedpendingmessageslist: setapprovedpendingmessageslist,
  callslist: setcallslist,
  pendingcallalerts: setpendingcallalerts,
  activeuserslist: setactiveuserslist,
  rejectcalls: setrejectedcalllist,
  mediatrackholder: setmediatrackholder,
  mediamyvideoholder: setmediamyvideoholder,
  postsfeedlist: setpostsfeedlist,
  istypinglist: setistypinglist,
  emojilist: setemojilist,
  minimizedconversation: setminimizedconversation,
  pagemodal: setpagemodal,
  usersettings: setusersettings,
  coordinates: setcoordinates,
  rawcoordinates: setrawcoordinates,
  previewparticipants: setpreviewparticipant,
});

const store = createStore(combiner);

export default store;
