export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const SET_ALERTS = 'SET_ALERTS';

export const SET_CONTACTS_LIST = 'SET_CONTACTS_LIST';

export const SET_NOTIFICATIONS_LIST = 'SET_NOTIFICATIONS_LIST';

export const SET_MESSAGES_LIST = 'SET_MESSAGES_LIST';

export const SET_TOGGLE_RIGHT_WIDGET = 'SET_TOGGLE_RIGHT_WIDGET';
export const SET_CONVERSATION_SETUP = 'SET_CONVERSATION_SETUP';