export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const SET_ALERTS = 'SET_ALERTS';
export const SET_MUTATE_ALERTS = 'SET_MUTATE_ALERTS';
export const SET_FILTERED_ALERTS = 'SET_FILTERED_ALERTS';
export const SET_CLEAR_ALERTS = 'SET_CLEAR_ALERTS';

export const SET_PENDING_CALL_ALERTS = 'SET_PENDING_CALL_ALERTS';
export const REMOVE_PENDING_CALL_ALERTS = 'REMOVE_PENDING_CALL_ALERTS';
export const CLEAR_PENDING_CALL_ALERTS = 'CLEAR_PENDING_CALL_ALERTS';

export const SET_CONTACTS_LIST = 'SET_CONTACTS_LIST';

export const SET_NOTIFICATIONS_LIST = 'SET_NOTIFICATIONS_LIST';

export const SET_MESSAGES_LIST = 'SET_MESSAGES_LIST';

export const SET_TOGGLE_RIGHT_WIDGET = 'SET_TOGGLE_RIGHT_WIDGET';
export const SET_CONVERSATION_SETUP = 'SET_CONVERSATION_SETUP';

export const SET_SCREEN_SIZE_LISTENER = 'SET_SCREEN_SIZE_LISTENER';
export const SET_PATHNAME_LISTENER = 'SET_PATHNAME_LISTENER';

export const SET_PENDING_MESSAGES_LIST = 'SET_PENDING_MESSAGES_LIST';
export const SET_APPROVED_PENDING_MESSAGES_LIST = 'SET_APPROVED_PENDING_MESSAGES_LIST';

export const SET_CALLS_LIST = 'SET_CALLS_LIST';
export const END_CALL_LIST = 'END_CALL_LIST';
export const SET_REJECTED_CALL_LIST = 'SET_REJECTED_CALL_LIST';
export const REMOVE_REJECTED_CALL_LIST = 'REMOVE_REJECTED_CALL_LIST';
export const CHECK_AND_ADD_NEW_CALL_LIST_WINDOW = 'CHECK_AND_ADD_NEW_CALL_LIST_WINDOW';
export const MEDIA_TRACK_HOLDER = 'MEDIA_TRACK_HOLDER';
export const MEDIA_MY_VIDEO_HOLDER = 'MEDIA_MY_VIDEO_HOLDER';

export const SET_ACTIVE_USERS_LIST = 'SET_ACTIVE_USERS_LIST';
export const UPDATE_ACTIVE_USERS_LIST = 'UPDATE_ACTIVE_USERS_LIST';

export const SET_POSTS_FEED_LIST = 'SET_POSTS_FEED_LIST';
export const SET_MUTATE_POSTS_FEED_LIST = 'SET_MUTATE_POSTS_FEED_LIST';